apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: op-ingress
  namespace: openproject
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: openproject.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: op-web
                port:
                  number: 80