apiVersion: v1
kind: ConfigMap
metadata:
  name: op-config
  namespace: openproject
data:
  OPENPROJECT_HOST__NAME: "openproject.example.com"
  OPENPROJECT_HTTPS: "true"
  OPENPROJECT_LOG__LEVEL: "info"